### ISSUE TITLE
网上找了很多wifi插座

### ISSUE THREAD

**Issue by sxyandapp** [xiaolongba/wifi_outlet_for_open_source#1]
网上找了很多wifi插座，希望能找到一款硬件的wifi插座，然后自己能编程进去，毕竟不是每个人都有条件做硬件。好容易在github上找到了题主的这个东西，结果还是个太监，只有设计，没硬件产出。

**Comment by xiaolongba** [comment]
@sxyandapp 这位兄台为啥如此动怒?硬件layout以及结构我们都已经设计完成了，我们的目的是要做一个有app，有云，有固件的开源项目，现在缺少app的相关人员.暂时没进展

**Comment by sxyandapp** [comment]
> @sxyandapp 这位兄台为啥如此动怒?硬件layout以及结构我们都已经设计完成了，我们的目的是要做一个有app，有云，有固件的开源项目，现在缺少app的相关人员.暂时没进展

硬件有厂家或个人做出来没，我想买几个。前两天买两个阿里智能的，结果弄了半天没拆开

**Comment by xiaolongba** [comment]
@sxyandapp 有，几有几个样品我们暂时不卖，不好意思

**Comment by sxyandapp** [comment]
app有需求说明书没，我可以做app

**Comment by xiaolongba** [comment]
@sxyandapp 加那个群，我里面有这些
